### ISSUE TITLE
Building on Unix?

### ISSUE THREAD

**Issue by timonsku** [adafruit/seesaw#2]
I was wondering if there are any dependencies that make the code tied to Atmel Studio (or at least make it harder to use something else) or if compiling with arm-gcc on say Linux should work just as well?

**Comment by deanm1278** [comment]
@PTS93 we use Atmel studio for stuff like debugging, build script management, etc.
It will compile just fine with arm-gcc (that's what Atmel studio uses behind the scenes) but currently you will need to create your own makefile.

**Comment by timonsku** [comment]
Thanks for the info and quick reply!

**Comment by deanm1278** [comment]
just saw this issue again. @PTS93 the build is makefile based now so you should be able to build on any system as long as arm-none-eabi compiler tools are in your PATH

**Comment by timonsku** [comment]
oh thats cool! I got by with Atmel Studio so far but as I primarily use Linux the make file is a great help, thanks!
