### ISSUE TITLE
Add Travis CI?

### ISSUE THREAD

**Issue by caternuson** [adafruit/seesaw#25]
Any reason to not have Travis setup for this repo? At least run a check to make sure everything builds:
https://github.com/caternuson/seesaw/blob/travis/.travis.yml

**Comment by ladyada** [comment]
it should - plz add!

**Comment by wallarug** [comment]
That would be great!

**Comment by caternuson** [comment]
Want me to PR what I've got? It's suuuuuuper basic. But can always grow with time.

**Comment by ladyada** [comment]
yes plz

**Comment by caternuson** [comment]
yeah. green check marks.

closing. added with #26
