### ISSUE TITLE
NMI_Handler in qxk_port.S is not invoked after PR#39 causing a hang in I2c transactions

### ISSUE THREAD

**Issue by eugeneanikin** [adafruit/seesaw#44]
I built "make BOARD=samd09Breakout" using latest code and "gcc version 10.2.1 20201103 (release) (GNU Arm Embedded Toolchain 10-2020-q4-major)"
The board stops reacting after the first i2c transaction. 
I traced the source of the problem to a PR#39. In startup_samd09.c NMI_Handler was renamed into NonMaskableInt_Handler, however qxk_port.S was not updated.

**Comment by ladyada** [comment]
thanks, can ya submit a PR?

**Comment by eugeneanikin** [comment]
Working on it...

**Comment by eugeneanikin** [comment]
PR#45
