### ISSUE TITLE
Inconsistent Seesaw license

### ISSUE THREAD

**Issue by simonlbn** [adafruit/seesaw#5]
Hi,

The LICENSE file in the seesaw repository says MIT license, but looking at the non-library source files they mostly have a GPLv3 header. Could either LICENSE file be updated to say GPLv3 or the headers be changed to MIT so there is less ambiguity?

Regards,
Simon

**Comment by deanm1278** [comment]
updated!
https://github.com/adafruit/seesaw/commit/3dfbf2254b2b533aea132cc1afdd642f115f3a35

**Comment by simonlbn** [comment]
Thanks!
