### ISSUE TITLE
Build fails - missing build_date.h

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/seesaw#7]
Trying to build for BOARD=crickit for BAORD=samd09Breakout fails due to missing include file.

```
In file included from lib/qp/extras/fw_log.cpp:36:0:
./include/SeesawConfig.h:7:10: fatal error: build_date.h: No such file or directory
 #include "build_date.h"
          ^~~~~~~~~~~~~~
compilation terminated.
Makefile:148: recipe for target 'build/crickit/lib/qp/extras/fw_log.o' failed
make: *** [build/crickit/lib/qp/extras/fw_log.o] Error 1
```

**Comment by deanm1278** [comment]
hey @jerryneedell, that file is auto-generated for each build when the make command is run. Make sure you have python in your path and can run
```python scripts/datecode.py .```
from the repo root directory

also if you're looking for the most recent crickit build the uf2 can be found here: https://github.com/adafruit/seesaw/releases/tag/1.1.2

**Comment by jerryneedell** [comment]
@deanm1278 Thanks - I was jsut testing to see if I could build it.
I tried:

python scripts/datecode.py .

and it runs ok but the build still fails.

When is the python script run to create build_date.h?

**Comment by deanm1278** [comment]
the script is run here: https://github.com/adafruit/seesaw/blob/master/Makefile#L120
when you run the python script does the build_date.h file get created in the repo root?

**Comment by jerryneedell** [comment]
No - nothing is created.

**Comment by deanm1278** [comment]
maybe a permissions issue and it can't create the file? Try running as root?

**Comment by jerryneedell** [comment]
it works if I make this change:
```
-f = open(sys.argv[1] + '\\build_date.h', 'w')
+f = open(sys.argv[1] + '/build_date.h', 'w')
 
```

**Comment by jerryneedell** [comment]
I am building on Linux (also tried MacOS)  is the script assuming Windows? (uses "\")

**Comment by deanm1278** [comment]
oh yea windows paths. We can probably remove those slashes entirely... I'll try on monday
does the rest of the build work once you fix that file?

**Comment by jerryneedell** [comment]
Yes - it seems to work fine with that change - No errors with 
make all-boards
Thanks - no rush on this. I just wanted to make sure I understood what was going on.

**Comment by deanm1278** [comment]
fixed!
https://github.com/adafruit/seesaw/commit/46764c7001897b8a43d3bbc0a83a40ecde81828b
