### ISSUE TITLE
Servo motor doesn't go to 0

### ISSUE THREAD

**Issue by danowall** [adafruit/seesaw#8]
In MakeCode, servo motor doesn't go all the way to 0 degrees when "crickit set servo angle to 0" is used. 

Using "crickit set servo pulse to 500" does send servo to 0 degrees, however.

**Comment by ladyada** [comment]
this isn't a bug, this is just how servos work :)
https://learn.adafruit.com/adafruit-crickit-creative-robotic-interactive-construction-kit/makecode-servos#precise-pulses

https://learn.adafruit.com/adafruit-crickit-creative-robotic-interactive-construction-kit/circuitpython-servos#min-slash-max-pulse-control

**Comment by danowall** [comment]
got it! thank you for these links, this is helpful.

**Comment by deanm1278** [comment]
hey @ladyada did we test that setAngle gives the same results as the corresponding function in cirpy or arduino?

**Comment by ladyada** [comment]
we didn't but we can. in cirpy you can adjust the min/max pulse in the servo library and i did that a lot.
we also default to 1-2ms in circuitpy
https://github.com/adafruit/Adafruit_CircuitPython_Motor/blob/master/adafruit_motor/servo.py#L43
